name: Bug Template
description: 버그 발생 및 발견 시 제보하는 템플릿
title: "[Bug]: 버그 이슈 제목"
labels: ["bug"]

body:
  - type: dropdown
    id: target
    attributes:
      label: Target Device
      description: 버그가 발생된 앱이 실행된 곳
      options:
        - Simulator
        - Device
    validations:
      required: true
           
  - type: textarea
    id: where-bug
    attributes:
      label: Related Page
      description: 버그와 발생한 페이지를 알려주세요.
      placeholder: ex. LoginSubmitView 
    validations:
      required: true
      
  - type: textarea
    id: what-bug
    attributes:
      label: Bug Report
      description: 어떤 버그인지 설명해주세요.
      placeholder: ex) 필수 입력 값인 id를 넣지 않아도 submit이 가능한 버그
    validations:
      required: true
      
  - type: textarea
    id: bug-flow
    attributes:
      label: Bug Flow(Optional)
      description: 버그가 발생하게 된 Flow를 알려주세요.
      placeholder: ex) 사용자가 로그인을 할 때 LoginSubmitView에서 id를 입력하지 않고 로그인을 한다.
    validations:
      required: true
      
